[colors.primary]
background = '#091516'
foreground = '#ffffff'

[colors.selection]
text = '#ffffff'
background = '#6fbd77'

[colors.cursor]
text = '#091516'
cursor = '#a8faad'

[colors.normal]
black   = '#091516'
red     = '#ff9572'
green   = '#7efa7d'
yellow  = '#ffef72'
blue    = '#90ed95'
magenta = '#6fbd77'
cyan    = '#a8faad'
white   = '#effff1'

[colors.bright]
black   = '#3b443c'
red     = '#ffb79f'
green   = '#a6ffa5'
yellow  = '#fff5a5'
blue    = '#b7ffbc'
magenta = '#c4ffc8'
cyan    = '#d9ffdb'
white   = '#f8fff9'
